---
title: "Ch1_Biomass_Estimates"
author: "Denise Colombano"
date: "March 4, 2017"
output: html_document
---

```{r, import dataframe}
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemes)
library(gcookbook)
library(grid)
library(plotrix)
library(plyr)

# read in csv file with abundance data for each age class (incl. NAs)
chapter1_ab <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_AgeClass_Abun_Estimates.txt")
View(chapter1_ab)
glimpse(chapter1_ab)

# read in csv file with length data (incl. NAs) in order to calculate biomass
# which will then be joined to the abundance dataframe
chapter1_lw <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_StandardLengths.txt")
View(chapter1_lw)
glimpse(chapter1_lw)
summary(chapter1_lw)

# filter year
chapter1_ab %>% 
  filter(Yr>=1995) %>% 
  summary

chapter1_lw <- chapter1_lw %>% 
  filter(SampleYear>=1995)

chapter1_lw$id <- 1:66973
```

STEP 1. Calculating biomass for measured fish

```{r, biomass calculations, test}

## Calculate biomass using two different methods and compare

# strategy 1: STEP BY STEP EQUATIONS
chapter1_ex <- chapter1_lw %>% 
  select(YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(AgeClass=="Age-0" & OrganismCode=="SB") %>% 
  mutate(sb0_g = StandardLength^3.25) %>% 
  mutate(sb0_g = sb0_g*0.0034) %>% 
  mutate(sb0_g = sb0_g *Count) %>% 
  mutate(sb0_g = sb0_g /1000) 

# strategy 2: SINGLE EQUATION
chapter1_ex2 <- chapter1_lw %>% 
  select(id, YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(AgeClass=="Age-0" & OrganismCode=="SB") %>% 
  mutate(sb0_g = (((StandardLength^3.25)*0.0034)*Count)/1000)

# strategy 3: SINGLE EQUATION
chapter1_ex3 <- chapter1_lw %>% 
  select(id, YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(AgeClass=="Age-0" & OrganismCode=="SB") %>% 
  group_by(id) %>% 
  mutate(sb0_g = ((StandardLength^3.25)*0.0034)*Count/1000)

# Compare the dataframes = **THE SAME**
View(chapter1_ex)
View(chapter1_ex2)
View(chapter1_ex3)

# Compare the plots = **THE SAME**
ex <- ggplot(chapter1_ex, aes(x=StandardLength, y=sb0_g)) + 
  geom_point() 
ex

ex3 <- ggplot(chapter1_ex3, aes(x=StandardLength, y=sb0_g)) + 
  geom_point() 
ex3
```

```{r, biomass calculations, for real}

## CALCULATIONS: Separate dataframes
# Age-0 Striped Bass
sb_biomass <- chapter1_lw %>% 
  select(YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(OrganismCode=="SB") %>% 
  mutate(sb0_g = ((StandardLength^3.25)*0.0034)*Count/1000)
glimpse(sb_biomass)
View(sb_biomass)

# Age-0 Splittail
st_biomass <- chapter1_lw %>% 
  select(YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(OrganismCode=="ST") %>% 
  mutate(st0_g = ((StandardLength^3.30)*0.0026)*Count/1000)
glimpse(st_biomass)

# Age-0 Tule Perch
tp_biomass <- chapter1_lw %>% 
  select(YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(OrganismCode=="TP") %>% 
  mutate(tp0_g = ((StandardLength^2.96)*0.0289)*Count/1000)
glimpse(tp_biomass)

# Age-0 Starry Flounder
sf_biomass <- chapter1_lw %>% 
  select(YrMoSite, YearMo, StationCode, SampleYear, YrMoSpp, OrganismCode, Count, StandardLength, AgeClass) %>% 
  filter(OrganismCode=="SF") %>% 
  mutate(sf0_g = ((StandardLength^3.13)*0.0082)*Count/1000)
glimpse(sf_biomass)

## double check plots
ggplot(sb_biomass, aes(x=StandardLength, y=sb0_g)) + 
  geom_point()
ggplot(st_biomass, aes(x=StandardLength, y=st0_g)) + 
  geom_point()
ggplot(tp_biomass, aes(x=StandardLength, y=tp0_g)) + 
  geom_point()
ggplot(sf_biomass, aes(x=StandardLength, y=sf0_g)) + 
  geom_point()


## CONVERT TO LONGFORM DF: Double check that each DF has 1:5223 rows to make sure zeros are present!
# The joined biomass DF only has estimated biomass for measured fish; need to add plus-counted fish after.

# striped bass
sb_biomass_sum <- sb_biomass %>% 
  select(YrMoSite:SampleYear, sb0_g) %>% 
  group_by(YrMoSite) %>% 
  summarize(sb0_b = sum(sb0_g))
View(sb_biomass_sum)

# splittail
st_biomass_sum <- st_biomass %>% 
  select(YrMoSite:SampleYear, st0_g) %>% 
  group_by(YrMoSite) %>% 
  summarize(st0_b = sum(st0_g))
View(st_biomass_sum)

# tule perch
tp_biomass_sum <- tp_biomass %>% 
  select(YrMoSite:SampleYear, tp0_g) %>% 
  group_by(YrMoSite) %>% 
  summarize(tp0_b = sum(tp0_g))
View(tp_biomass_sum)

# starry flounder
sf_biomass_sum <- sf_biomass %>% 
  select(YrMoSite:SampleYear, sf0_g) %>% 
  group_by(YrMoSite) %>% 
  summarize(sf0_b = sum(sf0_g))
View(sf_biomass_sum)

## INNER JOIN
biomass_joined <- sb_biomass_sum %>%
  inner_join(st_biomass_sum, by="YrMoSite")

biomass_joined <- biomass_joined %>% 
  inner_join(tp_biomass_sum, by="YrMoSite")

biomass_joined <- biomass_joined %>% 
  inner_join(sf_biomass_sum, by="YrMoSite")
```


STEP 2. Calculating estimated biomass for unmeasured fish

```{r, add estimated lengths to unmeasured fish, in order to calculate biomass later}
## CALCULATE Average SL at each YrMoSite
mean_sl_age0<- chapter1_lw %>% 
  select(YrMoSite, YearMo, YrMoSpp, OrganismCode, AgeClass, StandardLength) %>% 
  #unite(YrMoSppAge, YrMoSpp, AgeClass, sep="_") %>% # create a new unique identifier
  filter(AgeClass=="Age-0") %>% 
  group_by(YrMoSpp) %>% 
  summarize(mean_sl_age0=mean(StandardLength))
head(mean_sl_age0)
```

```{r, tidy data in chapter1_ab DF}
# Query unmeasured fish and their estimated age classes
unmsr_age0 <- chapter1_ab %>% 
  select(YrMoSite:YrMoSpp,OrganismCode, Unmsrd, `Est_Age-0`)
head(unmsr_age0)

# Inner join - add estimated mean length for age-0 fish at each year+mo combination
unmsr_age0_length_joined <- unmsr_age0 %>% 
  inner_join(mean_sl_age0, by="YrMoSpp")
View(unmsr_age0_length_joined)
```


```{r}
# Create a DF that has estimated biomass for each estimated length for unmeasured fish
# Step 1. Create sub-DF with estimated biomass for each species

# Unmeasured age-0 fish
unmsr_age0_sb <- unmsr_age0_length_joined %>% 
  filter(OrganismCode=="SB") %>% 
  mutate(sb0_b_est = ((mean_sl_age0^3.25)*0.0034)*`Est_Age-0`/1000) %>% 
  select(YrMoSite, sb0_b_est)
View(unmsr_age0_sb)

unmsr_age0_st <- unmsr_age0_length_joined %>% 
  filter(OrganismCode=="ST") %>% 
  mutate(st0_b_est = ((mean_sl_age0^3.30)*0.0026)*`Est_Age-0`/1000)%>% 
  select(YrMoSite, st0_b_est)
View(unmsr_age0_st)

unmsr_age0_tp <- unmsr_age0_length_joined %>% 
  filter(OrganismCode=="TP") %>% 
  mutate(tp0_b_est = ((mean_sl_age0^2.96)*0.0289)*`Est_Age-0`/1000)%>% 
  select(YrMoSite, tp0_b_est)
View(unmsr_age0_tp)

unmsr_age0_sf <- unmsr_age0_length_joined %>% 
  filter(OrganismCode=="SF") %>% 
  mutate(sf0_b_est = ((mean_sl_age0^3.13)*0.0082)*`Est_Age-0`/1000)%>% 
  select(YrMoSite, sf0_b_est)
View(unmsr_age0_sf)

# Convert to longform DF

unmsr_age0_weight <- unmsr_age0_sb %>% 
  inner_join(unmsr_age0_st, by="YrMoSite")

unmsr_age0_weight <- unmsr_age0_weight %>% 
  inner_join(unmsr_age0_tp, by="YrMoSite")

unmsr_age0_weight <- unmsr_age0_weight %>% 
  inner_join(unmsr_age0_sf, by="YrMoSite")

## JOIN WITH BIOMASS of measured fish
# measured and unmeasured together
biomass_all_joined <- biomass_joined %>% 
  join(unmsr_age0_weight, by="YrMoSite", match="all") # use join from plyr to maintain 5223 rows in DF

# calculate total biomass for age0 fish (both measured and unmeasured)
biomass_all_sum <- biomass_all_joined %>% 
  group_by(YrMoSite) %>% 
  summarise(sb0_b_tot = sb0_b + sb0_b_est, st0_b_tot = st0_b + st0_b_est, tp0_b_tot = tp0_b + tp0_b_est, sf0_b_tot = sf0_b + sf0_b_est)

# fill in NAs with zeroes
biomass_all_sum[is.na(biomass_all_sum)] <- 0
```


STEP 3. ADD TO REGULAR DF
```{r}
chapter1 <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_Abun_Biom_Growth.txt")
View(chapter1)
glimpse(chapter1)
chapter1$id <- 1:5223
str(chapter1)
summary(chapter1)

chapter1 %>% 
  inner_join(biomass_all_sum, yr="YrMoSite") %>% 
  write.csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_BiomassEstimates_Age0.csv", row.names=FALSE)

chapter1_bio <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_BiomassEstimates_Age0.csv")
```


