---
title: "Ch1_Abundance_1995-2016_Merge_RedoUnmsrd"
author: "Denise Colombano"
date: "May 30, 2017"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(magrittr)
library(ggthemes)
library(gcookbook)
library(grid)
library(plotrix)
library(readr)

# read in CSV file with 5465 rows
#chapter1 <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_Abundance.txt")

# read in CSV file -- filter to 57658 rows
rawdata <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_Ch1_StandardLengths_1995-2016.txt") # AKA chapter1_lw
rawdata <- rawdata %>% 
  unite(YrMoSite,c(YearMo,StationCode), sep="_", remove=FALSE) %>% 
  filter(SampleYear>1994, MethodCode=="OTR") 
rawdata$YrMoSite <- as.factor(rawdata$YrMoSite)
```

```{r, TOC}
# The point of this script is to re-run the analysis to estimate age classes for the following sites: DV2 and SU1.
# For some odd reason, there was dirty no good beach seine data in the last version and it was fucking with 
# my abundance estimates and making me cry.

# All of the data on DV2 and SU1 in the MS Access table, "04_AgeClass_Abund_1995-2016" is to be deleted and appended with the following:

# Note: The reason I don't run this code for the whole dataset is because and I quote a warning I left for myself a few months ago, "## Don't do this for the whole dataset because there were >600 records where I had to reference datasheets for notes such as "100 splittail over 50mm" and it's more accurate that way."
```


```{r, Step 1.}
# create a subset for all future analysis in this exercise -- ONLY SU1 AND DV2
rawdata_subset <- rawdata %>% 
  filter(StationCode=="DV2" | StationCode=="SU1") %>% 
  select(MethodCode, YearMo, StationCode, OrganismCode, StandardLength, AgeClass, Count) %>% 
  unite(YrMoSite, c(YearMo,StationCode), sep="_", remove=FALSE)

# create another template with YrMoSite - 253 from 2016
surveys <- rawdata_subset %>% 
  select(YrMoSite, YearMo, StationCode, Count) %>% 
  group_by(YrMoSite, YearMo) %>% 
  summarize(sum(Count)) %>% 
  select(YrMoSite, YearMo)

# query the number of rows that have unmeasured fish, for future estimation = 60
rawdata_unmsrd <- rawdata_subset %>% 
  select(YrMoSite:OrganismCode, AgeClass, Count) %>% 
  filter(is.na(AgeClass), Count>0) %>%
  select(YrMoSite:OrganismCode, Count) 

View(rawdata_unmsrd) 

# query the number of rows that have measured fish = 1277
rawdata_msrd <- rawdata_subset %>% 
  filter(!is.na(AgeClass)) %>% 
  select(YrMoSite:OrganismCode, AgeClass, Count) %>% 
  group_by(YrMoSite, OrganismCode, AgeClass) %>% 
  summarize(Count = sum(Count))
View(rawdata_msrd) 
```

```{r, sum of counts for measured fish}
# striped bass
sb_msrd <- rawdata_msrd %>% 
  filter(OrganismCode=="SB", !is.na(AgeClass)) %>% 
  spread(AgeClass, Count, fill=0, convert=FALSE) %>% 
  rename(sb0=`Age-0`, sb1=`Age-1`, sb2=`Age-2+`) 

# splittail
st_msrd <- rawdata_msrd %>% 
  filter(OrganismCode=="ST", !is.na(AgeClass)) %>% 
  spread(AgeClass, Count, fill=0, convert=FALSE) %>% 
  rename(st0=`Age-0`, st1=`Age-1`, st2=`Age-2+`)

# tule perch
# striped bass
tp_msrd <- rawdata_msrd %>% 
  filter(OrganismCode=="TP", !is.na(AgeClass)) %>% 
  spread(AgeClass, Count, fill=0, convert=FALSE) %>% 
  rename(tp0=`Age-0`, tp1=`Age-1+`)

# striped bass
sf_msrd <- rawdata_msrd %>% 
  filter(OrganismCode=="SF", !is.na(AgeClass)) %>% 
  spread(AgeClass, Count, fill=0, convert=FALSE) %>% 
  rename(sf0=`Age-0`, sf1=`Age-1`)

# join them back together
sum_msrd <- surveys %>% 
  full_join(sb_msrd, by="YrMoSite") %>% 
  full_join(st_msrd, by="YrMoSite") %>% 
  full_join(tp_msrd, by="YrMoSite") %>% 
  full_join(sf_msrd, by="YrMoSite") %>% 
  select(YrMoSite, YearMo, sb0, sb1, sb2, st0, st1, st2, tp0, tp1, sf0, sf1)

sum_msrd[is.na(sum_msrd)] <- 0
```


```{r}
# mean SL
mean_sl_all<- rawdata %>% 
  select(YrMoSite, YearMo, OrganismCode, AgeClass, StandardLength) %>% 
  filter(!is.na(AgeClass)) %>% 
  group_by(OrganismCode, YearMo, AgeClass) %>% 
  summarize(mean_sl=mean(StandardLength)) 

# change this to a character to match it to unmeasured fish later
mean_sl_all$YearMo <- as.character(mean_sl_all$YearMo)

# calculate proportion of age classes for each age class+month
ageclass_prop <- sum_msrd %>% 
  select(YearMo, sb0:sf1) %>% 
  group_by(YearMo) %>% 
  summarize(sb0=sum(sb0), sb1=sum(sb1), sb2=sum(sb2), st0=sum(st0), st1=sum(st1), st2=sum(st2), tp0=sum(tp0), tp1=sum(tp1), sf0=sum(sf0), sf1=sum(sf1)) %>% 
  mutate(sb_tot=sb0+sb1+sb2, st_tot=st0+st1+st2, tp_tot=tp0+tp1, sf_tot=sf0+sf1 ) %>% 
  mutate(sb0_p=sb0/sb_tot, sb1_p=sb1/sb_tot, sb2_p=sb2/sb_tot, st0_p=st0/st_tot, st1_p=st1/st_tot, st2_p=st2/st_tot, tp0_p=tp0/tp_tot, tp1_p=tp1/tp_tot, sf0_p=sf0/sf_tot, sf1_p=sf1/sf_tot)

ageclass_prop[is.na(ageclass_prop)] <- 0

# dataframe with estimated proportions for each month+site combo            
sum_msrd_prop <- ageclass_prop %>% 
  select(YearMo, sb0_p:sf1_p) %>% 
  full_join(sum_msrd, by="YearMo")

# now it's time to take the unmeasured counts and multiply by estimated proportions
unmsrd_estimates <- rawdata_unmsrd %>% 
  left_join(ageclass_prop, by="YearMo", "YrMoSite") %>% 
  select(YrMoSite, OrganismCode, Count, sb0_p:sf1_p)

# striped bass
unmsrd_estimates_sb <- unmsrd_estimates %>% 
  filter(OrganismCode=="SB") %>% 
  group_by(YrMoSite) %>% 
  mutate(sb0_unmsr=Count*sb0_p, sb1_unmsr=Count*sb1_p, sb2_unmsr=Count*sb2_p) %>% 
  select(YrMoSite, sb0_unmsr:sb2_unmsr) 

# splittail
unmsrd_estimates_st <- unmsrd_estimates %>% 
  filter(OrganismCode=="ST") %>% 
  group_by(YrMoSite) %>% 
  mutate(st0_unmsr=Count*st0_p, st1_unmsr=Count*st1_p, st2_unmsr=Count*st2_p) %>% 
  select(YrMoSite, st0_unmsr:st2_unmsr) 

# tule perch
unmsrd_estimates_tp <- unmsrd_estimates %>% 
  filter(OrganismCode=="TP") %>% 
  group_by(YrMoSite) %>% 
  mutate(tp0_unmsr=Count*tp0_p, tp1_unmsr=Count*tp1_p) %>% 
  select(YrMoSite, tp0_unmsr:tp1_unmsr) 

# put them back together -AGAIN- before your brain bleeds out
unmsrd_estimates_joined <- unmsrd_estimates_sb %>% 
  full_join(unmsrd_estimates_st, by="YrMoSite") %>% 
  full_join(unmsrd_estimates_tp, by="YrMoSite") %>% 
  mutate_each(funs(round(.,0)), sb0_unmsr:tp1_unmsr) # round the values down to a whole number

unmsrd_estimates_joined[is.na(unmsrd_estimates_joined)] <- 0

unmsrd_all <- unmsrd_estimates_joined # look at bottom of script, this will be used for biomass estimates

# join with "sum_msrd" in order to add them together
sum_msrd_unmsrd <- sum_msrd %>% 
  full_join(unmsrd_estimates_joined, by="YrMoSite")
sum_msrd_unmsrd[is.na(sum_msrd_unmsrd)] <- 0 # this is fucking crucial or else it will skip the NAs!!
sum_msrd_unmsrd <- sum_msrd_unmsrd %>% 
  mutate(sb0_tot=sb0+sb0_unmsr, sb1_tot=sb1+sb1_unmsr, sb2_tot=sb2+sb2_unmsr, st0_tot=st0+st0_unmsr, st1_tot=st1+st1_unmsr, st2_tot=st2+st2_unmsr, tp0_tot=tp0+tp0_unmsr, tp1_tot=tp1+tp1_unmsr, sf0_tot=sf0, sf1_tot=sf1, sf2_tot=0) 
glimpse(sum_msrd_unmsrd)

# double check number of rows
doublechk_dv2 <- sum_msrd_unmsrd %>% 
  separate(YrMoSite,c("YrMo","StationCode")) %>% 
  filter(StationCode=="DV2")

doublechk_su1 <- sum_msrd_unmsrd %>% 
  separate(YrMoSite,c("YrMo","StationCode")) %>% 
  filter(StationCode=="SU1")

# write CSV file to store the data (msrd, unmsrd, total)
chapter1_dv2_su1 <- sum_msrd_unmsrd %>% 
 write_csv("~/GitHub/suisunmarsh/Ch1/Data_output/Data_Ch1_Msrd_Unmsrd_1995-2016_Redo_DV2_SU1.csv")
```

```{r}
# read it back into the script to create a datasheet to append the MS Access DB
#chapter1_dv2_su1 <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_output/Data_Ch1_Msrd_Unmsrd_1995-2016_Redo_DV2_SU1.csv")

# change the column names to match Access
append_access <- chapter1_dv2_su1 %>% 
  select(YrMoSite,sb0_tot:sf2_tot) %>% 
  rename(`ST_Age-0`=st0_tot, `SB_Age-0`=sb0_tot, `SF_Age-0`=sf0_tot, `TP_Age-0`=tp0_tot, `ST_Age-1`=st1_tot, `SB_Age-1`=sb1_tot, `SF_Age-1`=sf1_tot, `TP_Age-1+`=tp1_tot, `ST_Age-2+`=st2_tot, `SB_Age-2+`=sb2_tot, `SF_Age-2+`=sf2_tot) %>% 
  write_csv("~/GitHub/suisunmarsh/Ch1/Data_output/Data_Ch1_Msrd_Unmsrd_1995-2016_Redo_DV2&SU1_AppendAccess.csv")
  
# now use this to update the MS Access DB as a starting point for redoing the remaining analyses
```

```{r}
# calculate biomass for measured and unmeasured fish? See file "BiomassEstimates"
```

```{r, JOIN DV2/SU1 Data with the rest of the unmeasured data}
# this is the dataset you WANT your dataframe to match. 
# Use it as a template:
unmsrd <- read_csv("~/GitHub/suisunmarsh/Ch1/Data_output/Data_Ch1_Unmsrd_LW_1995-2016.csv")

View(unmsrd) # 958 rows in longform
```

```{r}
View(unmsrd_all) # 59 rows

# this is to create a longform dataframe with Dv2/DV3/SU1 data 
unmsrd_sb <- unmsrd_all %>%
  mutate(Species="StripedBass", OrganismCode="SB") %>% 
  select(YrMoSite, OrganismCode, sb0_unmsr:sb2_unmsr) %>% 
  rename(`Age-0`=sb0_unmsr, `Age-1`=sb1_unmsr, `Age-2+`=sb2_unmsr) %>% 
  gather(AgeClass,Count,`Age-0`:`Age-2+`) %>% 
  filter(Count>0)

unmsrd_st <- unmsrd_all %>%
  mutate(Species="Splittail", OrganismCode="ST") %>% 
  select(YrMoSite, OrganismCode, st0_unmsr:st2_unmsr) %>% 
  rename(`Age-0`=st0_unmsr, `Age-1`=st1_unmsr, `Age-2+`=st2_unmsr) %>% 
  gather(AgeClass,Count,`Age-0`:`Age-2+`)%>% 
  filter(Count>0)

unmsrd_tp <- unmsrd_all %>%
  mutate(Species="TulePerch", OrganismCode="TP") %>% 
  select(YrMoSite, OrganismCode, tp0_unmsr:tp1_unmsr) %>% 
  rename(`Age-0`=tp0_unmsr, `Age-1`=tp1_unmsr) %>% 
  gather(AgeClass,Count,`Age-0`:`Age-1`)%>% 
  filter(Count>0)

#unmsrd_sf <- unmsrd_all %>%
 # mutate(Species="StarryFlounder") %>% 
  #select(YrMoSite, OrganismCode, sf0_unmsr:sf2_unmsr) %>% 
  #rename(`Age-0`=sf0_unmsr, `Age-1`=sf1_unmsr, `Age-2+`=sf2_unmsr) %>% 
  #gather(AgeClass,Count,`Age-0`:`Age-2+`)
  
# bind them together - 78 rows
unmsrd_all_2 <- bind_rows(unmsrd_st, unmsrd_sb)
unmsrd_all_2 <- bind_rows(unmsrd_all_2, unmsrd_tp)
unmsrd_all_2 <- unmsrd_all_2 

# add mean_sl to each YrMoSite by adding in the YearMo column and matchng to est length
unmsrd_all_mean <- unmsrd_all_2 %>% 
  separate(YrMoSite, c("YearMo", "StationCode"), "_", remove=FALSE) %>% 
  unite(YrMoSpp, c(YearMo,OrganismCode), remove=FALSE) %>% 
  left_join(mean_sl_all, by=c("YearMo", "OrganismCode", "AgeClass")) 

View(unmsrd_all_mean)

# join with dataframe from 1995-2016
unmsrd$YearMo <- as.character(unmsrd$YearMo)

unmsrd_all_yrs <- bind_rows(unmsrd, unmsrd_all_mean) %>% 
  select(YrMoSite:mean_sl)

# write CSV file for biomass estimates
unmsrd_total <- unmsrd_all_yrs %>% 
 write_csv("~/GitHub/suisunmarsh/Ch1/Data_output/Data_Ch1_Unmsrd_LW_1995-2016_Redo.csv")
```

```{r, Join together Mrsd & Unmsrd CSV files}

```

